### ISSUE TITLE
Front page: invalid complete skills count (same for every subject)

### ISSUE THREAD

**Issue by doodek** [eip-ewi/Skill-Circuits#2]
![image](https://github.com/eip-ewi/Skill-Circuits/assets/71927208/a9e64da9-72aa-4657-bd9b-4d53c6dff8df)

I logged in to Skill Circuits browsing my courses, and when I got back to the front page I saw that all of the courses have 63 out of [something] skills completed, which is correct only for one course.

Tried this on two machines with same result

Hope you may find this feedback useful,
Regards,
Bartłomiej Dudek, CSE BSc Y2 2023/2024

**Comment by RafayelGardishyan** [comment]
Can confirm:
![image](https://github.com/eip-ewi/Skill-Circuits/assets/13188514/48aa17b1-2560-462c-949b-2e2d7c8069d1)

**Comment by MrHug** [comment]
Thank you both for reporting :) We are aware of [the issue](https://gitlab.ewi.tudelft.nl/skill-circuits/skill-circuits/-/issues/129) and have [an MR](https://gitlab.ewi.tudelft.nl/skill-circuits/skill-circuits/-/merge_requests/145) open to fix it :) We hope we can merge and deploy this fix soon!

Closing this issue here, but if you have more questions/remarks, feel free to reach out in the issue linked above.
